# Generated by Django 5.0.2 on 2024-03-30 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likecomment_comment', to='Post.comment'),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='user',
            field=models.ManyToManyField(related_name='likecomment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_category', to='Post.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='errors',
            field=models.ManyToManyField(related_name='post_errors', to='Post.errors'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ManyToManyField(related_name='post_photo', to='Post.photo'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='Post.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='Post.post'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_post', to='Post.post'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='user',
            field=models.ManyToManyField(related_name='viwer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
